// Mock Week 2: Post-Week State (All Games Complete)
// Scenario: Tuesday morning - All games finished
// All games have status: "Final" with complete scores and full player statistics

const week2Data = {
  season: "mock",
  week: 2,
  scenario: "Post-Week State (All Games Complete)",
  timestamp: "2024-09-17T09:00:00Z", // Tuesday morning after Week 2
  
  games: [
    // Thursday Night Football
    {
      game_id: "mock_2024_02_BUF_MIA",
      week: 2,
      season: "mock",
      home_team: "MIA",
      away_team: "BUF",
      home_score: 24,
      away_score: 31,
      game_date: "2024-09-12T20:15:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Hard Rock Stadium"
    },
    
    // Sunday 1:00 PM Games
    {
      game_id: "mock_2024_02_KC_CIN",
      week: 2,
      season: "mock",
      home_team: "CIN",
      away_team: "KC",
      home_score: 20,
      away_score: 27,
      game_date: "2024-09-15T13:00:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Paycor Stadium"
    },
    {
      game_id: "mock_2024_02_DAL_NYG",
      week: 2,
      season: "mock",
      home_team: "NYG",
      away_team: "DAL",
      home_score: 17,
      away_score: 35,
      game_date: "2024-09-15T13:00:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "MetLife Stadium"
    },
    {
      game_id: "mock_2024_02_PHI_NO",
      week: 2,
      season: "mock",
      home_team: "NO",
      away_team: "PHI",
      home_score: 14,
      away_score: 28,
      game_date: "2024-09-15T13:00:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Caesars Superdome"
    },
    {
      game_id: "mock_2024_02_GB_IND",
      week: 2,
      season: "mock",
      home_team: "IND",
      away_team: "GB",
      home_score: 21,
      away_score: 24,
      game_date: "2024-09-15T13:00:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Lucas Oil Stadium"
    },
    {
      game_id: "mock_2024_02_BAL_LV",
      week: 2,
      season: "mock",
      home_team: "LV",
      away_team: "BAL",
      home_score: 17,
      away_score: 31,
      game_date: "2024-09-15T13:00:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Allegiant Stadium"
    },
    {
      game_id: "mock_2024_02_MIN_SF",
      week: 2,
      season: "mock",
      home_team: "SF",
      away_team: "MIN",
      home_score: 28,
      away_score: 24,
      game_date: "2024-09-15T13:00:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Levi's Stadium"
    },
    {
      game_id: "mock_2024_02_DET_TB",
      week: 2,
      season: "mock",
      home_team: "TB",
      away_team: "DET",
      home_score: 10,
      away_score: 21,
      game_date: "2024-09-15T13:00:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Raymond James Stadium"
    },
    
    // Sunday 4:00 PM Games
    {
      game_id: "mock_2024_02_LAR_ARI",
      week: 2,
      season: "mock",
      home_team: "ARI",
      away_team: "LAR",
      home_score: 21,
      away_score: 24,
      game_date: "2024-09-15T16:05:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "State Farm Stadium"
    },
    {
      game_id: "mock_2024_02_SEA_NE",
      week: 2,
      season: "mock",
      home_team: "NE",
      away_team: "SEA",
      home_score: 14,
      away_score: 23,
      game_date: "2024-09-15T16:05:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Gillette Stadium"
    },
    {
      game_id: "mock_2024_02_LAC_CAR",
      week: 2,
      season: "mock",
      home_team: "CAR",
      away_team: "LAC",
      home_score: 17,
      away_score: 26,
      game_date: "2024-09-15T16:05:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Bank of America Stadium"
    },
    {
      game_id: "mock_2024_02_NYJ_TEN",
      week: 2,
      season: "mock",
      home_team: "TEN",
      away_team: "NYJ",
      home_score: 13,
      away_score: 20,
      game_date: "2024-09-15T16:05:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Nissan Stadium"
    },
    
    // Sunday Night Football
    {
      game_id: "mock_2024_02_HOU_CHI",
      week: 2,
      season: "mock",
      home_team: "CHI",
      away_team: "HOU",
      home_score: 17,
      away_score: 19,
      game_date: "2024-09-15T20:20:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Soldier Field"
    },
    
    // Monday Night Football
    {
      game_id: "mock_2024_02_ATL_WAS",
      week: 2,
      season: "mock",
      home_team: "WAS",
      away_team: "ATL",
      home_score: 21,
      away_score: 24,
      game_date: "2024-09-16T20:15:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "FedExField"
    },
    {
      game_id: "mock_2024_02_CLE_DEN",
      week: 2,
      season: "mock",
      home_team: "DEN",
      away_team: "CLE",
      home_score: 28,
      away_score: 21,
      game_date: "2024-09-16T20:15:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Empower Field at Mile High"
    },
    {
      game_id: "mock_2024_02_PIT_JAX",
      week: 2,
      season: "mock",
      home_team: "JAX",
      away_team: "PIT",
      home_score: 13,
      away_score: 16,
      game_date: "2024-09-16T20:15:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "TIAA Bank Field"
    }
  ],
  
  // Player stats - comprehensive data for all positions
  playerStats: [
    // Quarterbacks
    {
      player_id: "4046",  // Josh Allen
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BUF_MIA",
      passing_yards: 352,
      passing_tds: 4,
      interceptions: 1,
      rushing_yards: 45,
      rushing_tds: 1,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "4035",  // Patrick Mahomes
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_KC_CIN",
      passing_yards: 289,
      passing_tds: 3,
      interceptions: 0,
      rushing_yards: 12,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "3139",  // Dak Prescott
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_DAL_NYG",
      passing_yards: 380,
      passing_tds: 4,
      interceptions: 0,
      rushing_yards: 8,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "3916",  // Lamar Jackson
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BAL_LV",
      passing_yards: 278,
      passing_tds: 2,
      interceptions: 0,
      rushing_yards: 72,
      rushing_tds: 1,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    
    // Running Backs
    {
      player_id: "3969",  // Christian McCaffrey
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_MIN_SF",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 145,
      rushing_tds: 2,
      receiving_yards: 56,
      receiving_tds: 0,
      receptions: 5,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "4034",  // Saquon Barkley
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_PHI_NO",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 112,
      rushing_tds: 1,
      receiving_yards: 42,
      receiving_tds: 1,
      receptions: 4,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "4045",  // Nick Chubb
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_CLE_DEN",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 89,
      rushing_tds: 0,
      receiving_yards: 18,
      receiving_tds: 0,
      receptions: 2,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    
    // Wide Receivers
    {
      player_id: "3328",  // Tyreek Hill
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BUF_MIA",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 12,
      rushing_tds: 0,
      receiving_yards: 185,
      receiving_tds: 2,
      receptions: 9,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "4037",  // CeeDee Lamb
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_DAL_NYG",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 156,
      receiving_tds: 2,
      receptions: 8,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "4038",  // Justin Jefferson
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_MIN_SF",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 98,
      receiving_tds: 1,
      receptions: 6,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "2543",  // Stefon Diggs
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BUF_MIA",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 112,
      receiving_tds: 1,
      receptions: 7,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    
    // Tight Ends
    {
      player_id: "1479",  // Travis Kelce
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_KC_CIN",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 89,
      receiving_tds: 1,
      receptions: 7,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "3214",  // Mark Andrews
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BAL_LV",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 76,
      receiving_tds: 1,
      receptions: 5,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    
    // Kickers
    {
      player_id: "1466",  // Justin Tucker
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BAL_LV",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 3,
      extra_points_made: 4,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "3205",  // Harrison Butker
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_KC_CIN",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 2,
      extra_points_made: 3,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    
    // Additional players with edge cases for testing
    {
      player_id: "4566",  // Player with exactly 175 rushing yards (3 point bonus threshold)
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_GB_IND",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 175,
      rushing_tds: 1,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    },
    {
      player_id: "4567",  // Player with exactly 175 receiving yards (3 point bonus threshold)
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_LAR_ARI",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 175,
      receiving_tds: 1,
      receptions: 10,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z",
      is_playing: true,
      game_status: "Final"
    }
  ],
  
  // DST stats - comprehensive defensive stats for all teams that played
  dstStats: [
    // Teams from Thursday Night Football
    {
      team_code: "BUF",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BUF_MIA",
      points_allowed: 24,
      yards_allowed: 340,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "MIA",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BUF_MIA",
      points_allowed: 31,
      yards_allowed: 380,
      sacks: 2,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    
    // Teams from Sunday games
    {
      team_code: "KC",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_KC_CIN",
      points_allowed: 20,
      yards_allowed: 295,
      sacks: 4,
      interceptions: 2,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "CIN",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_KC_CIN",
      points_allowed: 27,
      yards_allowed: 350,
      sacks: 1,
      interceptions: 0,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "DAL",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_DAL_NYG",
      points_allowed: 17,
      yards_allowed: 275,
      sacks: 5,
      interceptions: 2,
      fumbles_recovered: 1,
      defensive_tds: 1,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "NYG",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_DAL_NYG",
      points_allowed: 35,
      yards_allowed: 420,
      sacks: 1,
      interceptions: 0,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "PHI",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_PHI_NO",
      points_allowed: 14,
      yards_allowed: 250,
      sacks: 6,
      interceptions: 3,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "NO",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_PHI_NO",
      points_allowed: 28,
      yards_allowed: 365,
      sacks: 2,
      interceptions: 0,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "GB",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_GB_IND",
      points_allowed: 21,
      yards_allowed: 320,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "IND",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_GB_IND",
      points_allowed: 24,
      yards_allowed: 340,
      sacks: 2,
      interceptions: 1,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "BAL",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BAL_LV",
      points_allowed: 17,
      yards_allowed: 280,
      sacks: 4,
      interceptions: 2,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "LV",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_BAL_LV",
      points_allowed: 31,
      yards_allowed: 390,
      sacks: 1,
      interceptions: 0,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "MIN",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_MIN_SF",
      points_allowed: 28,
      yards_allowed: 365,
      sacks: 2,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "SF",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_MIN_SF",
      points_allowed: 24,
      yards_allowed: 325,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "DET",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_DET_TB",
      points_allowed: 10,
      yards_allowed: 215,
      sacks: 5,
      interceptions: 2,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 1,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "TB",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_DET_TB",
      points_allowed: 21,
      yards_allowed: 315,
      sacks: 2,
      interceptions: 0,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "LAR",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_LAR_ARI",
      points_allowed: 21,
      yards_allowed: 310,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "ARI",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_LAR_ARI",
      points_allowed: 24,
      yards_allowed: 335,
      sacks: 2,
      interceptions: 0,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "SEA",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_SEA_NE",
      points_allowed: 14,
      yards_allowed: 245,
      sacks: 4,
      interceptions: 2,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "NE",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_SEA_NE",
      points_allowed: 23,
      yards_allowed: 330,
      sacks: 2,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "LAC",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_LAC_CAR",
      points_allowed: 17,
      yards_allowed: 290,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "CAR",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_LAC_CAR",
      points_allowed: 26,
      yards_allowed: 355,
      sacks: 1,
      interceptions: 0,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "NYJ",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_NYJ_TEN",
      points_allowed: 13,
      yards_allowed: 260,
      sacks: 4,
      interceptions: 1,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "TEN",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_NYJ_TEN",
      points_allowed: 20,
      yards_allowed: 305,
      sacks: 2,
      interceptions: 0,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "HOU",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_HOU_CHI",
      points_allowed: 17,
      yards_allowed: 285,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "CHI",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_HOU_CHI",
      points_allowed: 19,
      yards_allowed: 295,
      sacks: 3,
      interceptions: 0,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "ATL",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_ATL_WAS",
      points_allowed: 21,
      yards_allowed: 310,
      sacks: 2,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "WAS",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_ATL_WAS",
      points_allowed: 24,
      yards_allowed: 330,
      sacks: 1,
      interceptions: 0,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "CLE",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_CLE_DEN",
      points_allowed: 28,
      yards_allowed: 360,
      sacks: 2,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "DEN",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_CLE_DEN",
      points_allowed: 21,
      yards_allowed: 305,
      sacks: 3,
      interceptions: 2,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "PIT",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_PIT_JAX",
      points_allowed: 13,
      yards_allowed: 255,
      sacks: 5,
      interceptions: 2,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    },
    {
      team_code: "JAX",
      week: 2,
      season: "mock",
      game_id: "mock_2024_02_PIT_JAX",
      points_allowed: 16,
      yards_allowed: 270,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-17T09:00:00Z"
    }
  ],
  
  // Metadata for this week scenario
  metadata: {
    scenario: "Post-Week State",
    description: "All games complete with final scores and full statistics",
    testFocus: [
      "Final scoring calculations",
      "Weekly winner determination", 
      "Stat accumulation accuracy",
      "DST scoring (fewest points/yards allowed)"
    ],
    expectedBehaviors: {
      allGamesFinal: true,
      allStatsComplete: true,
      weeklyWinnerDeterminable: true,
      top11PlayersIdentifiable: true
    }
  }
};

module.exports = week2Data;