// Mock Week 3: Mid-Sunday Games
// Scenario: Sunday 2:30 PM ET - Mixed game states
// - Thursday game: Final
// - Sunday 1:00 PM games: InProgress (3rd quarter, varying time)
// - Sunday 4:00 PM games: Scheduled
// - Sunday/Monday night games: Scheduled

const week3Data = {
  season: "mock",
  week: 3,
  scenario: "Mid-Sunday Games",
  timestamp: "2024-09-22T18:30:00Z", // Sunday 2:30 PM ET
  
  games: [
    // Thursday Night Football - COMPLETED
    {
      game_id: "mock_2024_03_NYJ_NE",
      week: 3,
      season: "mock",
      home_team: "NE",
      away_team: "NYJ",
      home_score: 13,
      away_score: 24,
      game_date: "2024-09-19T20:15:00Z",
      status: "Final",
      quarter: "Final",
      time_remaining: "0:00",
      venue: "Gillette Stadium"
    },
    
    // Sunday 1:00 PM Games - IN PROGRESS (3rd Quarter)
    {
      game_id: "mock_2024_03_KC_ATL",
      week: 3,
      season: "mock",
      home_team: "ATL",
      away_team: "KC",
      home_score: 14,
      away_score: 21,
      game_date: "2024-09-22T17:00:00Z",
      status: "InProgress",
      quarter: "3rd",
      time_remaining: "12:45",
      game_time: "3Q 12:45",
      venue: "Mercedes-Benz Stadium"
    },
    {
      game_id: "mock_2024_03_PHI_TB",
      week: 3,
      season: "mock", 
      home_team: "TB",
      away_team: "PHI",
      home_score: 7,
      away_score: 17,
      game_date: "2024-09-22T17:00:00Z",
      status: "InProgress",
      quarter: "3rd",
      time_remaining: "8:22",
      game_time: "3Q 8:22",
      venue: "Raymond James Stadium"
    },
    {
      game_id: "mock_2024_03_BUF_WAS",
      week: 3,
      season: "mock",
      home_team: "WAS",
      away_team: "BUF",
      home_score: 10,
      away_score: 24,
      game_date: "2024-09-22T17:00:00Z",
      status: "InProgress",
      quarter: "3rd",
      time_remaining: "5:30",
      game_time: "3Q 5:30",
      venue: "FedExField"
    },
    {
      game_id: "mock_2024_03_MIN_HOU",
      week: 3,
      season: "mock",
      home_team: "HOU",
      away_team: "MIN",
      home_score: 17,
      away_score: 14,
      game_date: "2024-09-22T17:00:00Z",
      status: "InProgress",
      quarter: "3rd",
      time_remaining: "10:15",
      game_time: "3Q 10:15",
      venue: "NRG Stadium"
    },
    {
      game_id: "mock_2024_03_DAL_ARI",
      week: 3,
      season: "mock",
      home_team: "ARI",
      away_team: "DAL",
      home_score: 13,
      away_score: 20,
      game_date: "2024-09-22T17:00:00Z",
      status: "InProgress",
      quarter: "3rd",
      time_remaining: "3:45",
      game_time: "3Q 3:45",
      venue: "State Farm Stadium"
    },
    {
      game_id: "mock_2024_03_GB_TEN",
      week: 3,
      season: "mock",
      home_team: "TEN",
      away_team: "GB",
      home_score: 7,
      away_score: 21,
      game_date: "2024-09-22T17:00:00Z",
      status: "InProgress",
      quarter: "3rd",
      time_remaining: "14:20",
      game_time: "3Q 14:20",
      venue: "Nissan Stadium"
    },
    {
      game_id: "mock_2024_03_IND_CHI",
      week: 3,
      season: "mock",
      home_team: "CHI",
      away_team: "IND",
      home_score: 10,
      away_score: 10,
      game_date: "2024-09-22T17:00:00Z",
      status: "InProgress",
      quarter: "3rd",
      time_remaining: "7:00",
      game_time: "3Q 7:00",
      venue: "Soldier Field"
    },
    {
      game_id: "mock_2024_03_NO_DEN",
      week: 3,
      season: "mock",
      home_team: "DEN",
      away_team: "NO",
      home_score: 21,
      away_score: 17,
      game_date: "2024-09-22T17:00:00Z",
      status: "InProgress",
      quarter: "3rd",
      time_remaining: "11:30",
      game_time: "3Q 11:30",
      venue: "Empower Field at Mile High"
    },
    
    // Sunday 4:00 PM Games - SCHEDULED
    {
      game_id: "mock_2024_03_BAL_LV",
      week: 3,
      season: "mock",
      home_team: "LV",
      away_team: "BAL",
      home_score: 0,
      away_score: 0,
      game_date: "2024-09-22T20:05:00Z",
      status: "Scheduled",
      quarter: null,
      time_remaining: null,
      venue: "Allegiant Stadium"
    },
    {
      game_id: "mock_2024_03_LAR_SF",
      week: 3,
      season: "mock",
      home_team: "SF",
      away_team: "LAR",
      home_score: 0,
      away_score: 0,
      game_date: "2024-09-22T20:25:00Z",
      status: "Scheduled",
      quarter: null,
      time_remaining: null,
      venue: "Levi's Stadium"
    },
    {
      game_id: "mock_2024_03_MIA_SEA",
      week: 3,
      season: "mock",
      home_team: "SEA",
      away_team: "MIA",
      home_score: 0,
      away_score: 0,
      game_date: "2024-09-22T20:05:00Z",
      status: "Scheduled",
      quarter: null,
      time_remaining: null,
      venue: "Lumen Field"
    },
    {
      game_id: "mock_2024_03_PIT_LAC",
      week: 3,
      season: "mock",
      home_team: "LAC",
      away_team: "PIT",
      home_score: 0,
      away_score: 0,
      game_date: "2024-09-22T20:25:00Z",
      status: "Scheduled",
      quarter: null,
      time_remaining: null,
      venue: "SoFi Stadium"
    },
    
    // Sunday Night Football - SCHEDULED
    {
      game_id: "mock_2024_03_CLE_NYG",
      week: 3,
      season: "mock",
      home_team: "NYG",
      away_team: "CLE",
      home_score: 0,
      away_score: 0,
      game_date: "2024-09-23T00:20:00Z",
      status: "Scheduled",
      quarter: null,
      time_remaining: null,
      venue: "MetLife Stadium"
    },
    
    // Monday Night Football - SCHEDULED
    {
      game_id: "mock_2024_03_JAX_CIN",
      week: 3,
      season: "mock",
      home_team: "CIN",
      away_team: "JAX",
      home_score: 0,
      away_score: 0,
      game_date: "2024-09-24T00:15:00Z",
      status: "Scheduled",
      quarter: null,
      time_remaining: null,
      venue: "Paycor Stadium"
    },
    {
      game_id: "mock_2024_03_DET_CAR",
      week: 3,
      season: "mock",
      home_team: "CAR",
      away_team: "DET",
      home_score: 0,
      away_score: 0,
      game_date: "2024-09-24T00:15:00Z",
      status: "Scheduled",
      quarter: null,
      time_remaining: null,
      venue: "Bank of America Stadium"
    }
  ],
  
  // Player stats - partial stats for in-progress games
  playerStats: [
    // Quarterbacks with partial game stats
    {
      player_id: "4035",  // Patrick Mahomes (KC @ ATL - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_KC_ATL",
      passing_yards: 187,
      passing_tds: 2,
      interceptions: 0,
      rushing_yards: 15,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress",
      game_quarter: "3rd",
      game_time_remaining: "12:45"
    },
    {
      player_id: "4046",  // Josh Allen (BUF @ WAS - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BUF_WAS",
      passing_yards: 245,
      passing_tds: 3,
      interceptions: 0,
      rushing_yards: 32,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress",
      game_quarter: "3rd",
      game_time_remaining: "5:30"
    },
    {
      player_id: "3139",  // Dak Prescott (DAL @ ARI - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_DAL_ARI",
      passing_yards: 198,
      passing_tds: 2,
      interceptions: 1,
      rushing_yards: 12,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress",
      game_quarter: "3rd",
      game_time_remaining: "3:45"
    },
    {
      player_id: "3916",  // Lamar Jackson (BAL @ LV - Scheduled)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BAL_LV",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: false,
      game_status: "Scheduled"
    },
    
    // Running Backs
    {
      player_id: "4034",  // Saquon Barkley (PHI @ TB - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_PHI_TB",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 78,
      rushing_tds: 1,
      receiving_yards: 22,
      receiving_tds: 0,
      receptions: 3,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress",
      game_quarter: "3rd",
      game_time_remaining: "8:22"
    },
    {
      player_id: "3969",  // Christian McCaffrey (LAR @ SF - Scheduled)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_LAR_SF",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: false,
      game_status: "Scheduled"
    },
    
    // Wide Receivers
    {
      player_id: "3328",  // Tyreek Hill (MIA @ SEA - Scheduled)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_MIA_SEA",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: false,
      game_status: "Scheduled"
    },
    {
      player_id: "4037",  // CeeDee Lamb (DAL @ ARI - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_DAL_ARI",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 89,
      receiving_tds: 1,
      receptions: 5,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress",
      game_quarter: "3rd",
      game_time_remaining: "3:45"
    },
    {
      player_id: "4038",  // Justin Jefferson (MIN @ HOU - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_MIN_HOU",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 67,
      receiving_tds: 0,
      receptions: 4,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress", 
      game_quarter: "3rd",
      game_time_remaining: "10:15"
    },
    {
      player_id: "2543",  // Stefon Diggs (BUF @ WAS - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BUF_WAS",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 102,
      receiving_tds: 1,
      receptions: 6,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress",
      game_quarter: "3rd",
      game_time_remaining: "5:30"
    },
    
    // Tight Ends
    {
      player_id: "1479",  // Travis Kelce (KC @ ATL - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_KC_ATL",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 72,
      receiving_tds: 1,
      receptions: 5,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress",
      game_quarter: "3rd",
      game_time_remaining: "12:45"
    },
    {
      player_id: "3214",  // Mark Andrews (BAL @ LV - Scheduled)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BAL_LV",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: false,
      game_status: "Scheduled"
    },
    
    // Kickers
    {
      player_id: "1466",  // Justin Tucker (BAL @ LV - Scheduled)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BAL_LV",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 0,
      extra_points_made: 0,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: false,
      game_status: "Scheduled"
    },
    {
      player_id: "3205",  // Harrison Butker (KC @ ATL - InProgress)
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_KC_ATL",
      passing_yards: 0,
      passing_tds: 0,
      interceptions: 0,
      rushing_yards: 0,
      rushing_tds: 0,
      receiving_yards: 0,
      receiving_tds: 0,
      receptions: 0,
      field_goals_made: 2,
      extra_points_made: 1,
      return_tds: 0,
      sacks: 0,
      def_interceptions: 0,
      fumbles_recovered: 0,
      def_touchdowns: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z",
      is_playing: true,
      game_status: "InProgress",
      game_quarter: "3rd",
      game_time_remaining: "12:45"
    }
  ],
  
  // DST stats - partial stats for in-progress games
  dstStats: [
    // Completed Thursday game
    {
      team_code: "NYJ",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_NYJ_NE",
      points_allowed: 13,
      yards_allowed: 285,
      sacks: 4,
      interceptions: 2,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "NE",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_NYJ_NE",
      points_allowed: 24,
      yards_allowed: 345,
      sacks: 2,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    
    // In-Progress games (partial stats)
    {
      team_code: "KC",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_KC_ATL",
      points_allowed: 14,
      yards_allowed: 195,
      sacks: 2,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "ATL",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_KC_ATL",
      points_allowed: 21,
      yards_allowed: 245,
      sacks: 1,
      interceptions: 0,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "PHI",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_PHI_TB",
      points_allowed: 7,
      yards_allowed: 145,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "TB",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_PHI_TB",
      points_allowed: 17,
      yards_allowed: 220,
      sacks: 1,
      interceptions: 0,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "BUF",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BUF_WAS",
      points_allowed: 10,
      yards_allowed: 180,
      sacks: 3,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "WAS",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BUF_WAS",
      points_allowed: 24,
      yards_allowed: 315,
      sacks: 0,
      interceptions: 0,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "DAL",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_DAL_ARI",
      points_allowed: 13,
      yards_allowed: 205,
      sacks: 2,
      interceptions: 0,
      fumbles_recovered: 1,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "ARI",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_DAL_ARI",
      points_allowed: 20,
      yards_allowed: 280,
      sacks: 1,
      interceptions: 1,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    
    // Scheduled games - no stats yet
    {
      team_code: "BAL",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BAL_LV",
      points_allowed: 0,
      yards_allowed: 0,
      sacks: 0,
      interceptions: 0,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    },
    {
      team_code: "LV",
      week: 3,
      season: "mock",
      game_id: "mock_2024_03_BAL_LV",
      points_allowed: 0,
      yards_allowed: 0,
      sacks: 0,
      interceptions: 0,
      fumbles_recovered: 0,
      defensive_tds: 0,
      safeties: 0,
      last_updated: "2024-09-22T18:30:00Z"
    }
  ],
  
  // Metadata for this week scenario
  metadata: {
    scenario: "Mid-Sunday Games",
    description: "Mixed game states with live scoring in progress",
    testFocus: [
      "Live scoring updates",
      "Partial week scoring",
      "In-progress game display",
      "Real-time stat accumulation"
    ],
    expectedBehaviors: {
      hasInProgressGames: true,
      hasCompletedGames: true,
      hasScheduledGames: true,
      shouldAutoRefresh: true,
      refreshInterval: 30000 // 30 seconds
    }
  }
};

module.exports = week3Data;